config/routes.rb
Rails.application.routes.draw do
  get 'finances/index'

  get 'finances/show'

  get 'sessions/new'

  get    'finances/u_search/:id' => 'finances#u_search', as: 'u_search'

  get    'finances/a_search/:id' => 'finances#a_search', as: 'a_search'

  get    'orderinfos'      => 'orderinfos#index'

  get    'orderinfos/:id'  => 'orderinfos#show' , as: 'orderinfo'

  get    'orders/:id'      => 'orders#show', as: 'order'

  get    'orders/:id/update'      => 'orders#update', as: 'update'

  root   'pages#home'

  get    'users/new'       =>  'users#new', as: 'signup'

  get    'users/:id'       =>  'users#show', as: 'user'
  
  get    'users'           =>  'users#index'

  get    'users/:id/edit'  =>  'users#edit'

  get    'accounts/new', as: 'create_account'

  get    'accounts/:id/edit'   =>  'accounts#edit', as:'change_password'

  get    'accounts/:id'    =>  'accounts#show', as: 'account'

  get    'orders'          =>  'orders#index'

  get    'login'           =>  'sessions#new'

  post   'login'           =>  'sessions#create'

  delete 'logout'          =>  'sessions#destroy'

  namespace :api do
    get 'finances/search'           =>  'finances#search'
    get 'finances/count'            =>  'finances#count'
    resources :finances
  end

  resources :users, :accounts, :orders, :orderinfos

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :basics, as: :finance
  has_many :accounts
  has_many :orders, through: :u_orelations
  has_many :u_orelations
  has_secure_password
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
      format: {with:VALID_EMAIL_REGEX},uniqueness: { case_sensitive: false }
  validates :phone, length: {maximum: 13}
  validates :password, presence: true, length: { minimum: 6 },allow_nil: true

 #返回指定字符串的哈希摘要
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
 #返回一个随机令牌
  def User.new_token
    SecureRandom.urlsafe_base64
  end

 #为了持久会话,在数据库中记住用户
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
 #如果指定的令牌和摘要匹配,返回 true
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

 # 忘记用户
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in_user,only: [:new,:create]
  include UsersHelper
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash.now[:success] = "欢迎使用本管理系统"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:success] = "更新成功"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @accounts = @user.accounts
    @orders = @user.orders
  end

  def index
    search_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash.now[:success] = "用户删除成功"
    redirect_to users_url
  end

private
  def user_params
    params.require(:user).permit(:username, :email,:user_type,:real_name,:phone,:idcard, :password,:password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  REAL_NAME_REGEX = /\A([a-zA-z]+)|([a-zA-z]+\s+)\z/
  USER_TYPE_REGEX = /\A[123]\z/
  PHONE_REGEX = /(\d{0,9})|(\d{13})/
  def search_user
    if params[:search].present? && params[:commit] == "搜索"
      if params[:search] == "管理员"
        params[:search] = "3"
      elsif params[:search] == "用户"
        params[:search] = "1"
      elsif params[:search] == "商户"
        params[:search] = "2"
      end

      if params[:search] =~ EMAIL_REGEX
        user = User.where(:email => params[:search])
      elsif params[:search] =~ REAL_NAME_REGEX
        user = User.where(:real_name => params[:search])
      elsif params[:search] =~ USER_TYPE_REGEX
        user = User.where(:user_type => params[:search])
      elsif params[:search] =~ PHONE_REGEX
        user = User.where(:phone => params[:search])
      end
      @users = user.paginate(page: params[:page]).per_page(10)
    elsif params[:search].nil? && params[:commit] == "搜索"
      @users = {}
    elsif params[:search].nil? && params[:commit].nil?
      @users = User.paginate(page: params[:page]).per_page(10)
    end
  end

end

app/views/users/_accounts.html.erb
<div class="c_acc_h">
  <div class="c_acc">
    <%= link_to"绑定账户",create_account_path(@user),class: "btn btn-primary btn-sm active", role: "button" %>
  </div>
</div>
<% unless @accounts.empty? %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>账户名</th>
      <th>账户类型</th>
      <th>账户号</th>
      <th>账户所属银行</th>
      <th>银行电话</th>
      <th>所属地区</th>
      <th>余额</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <% @accounts.each do |account| %>
        <tr>
          <td><%= link_to account.bank_account, account_path(account) %></td>
          <% if account.account_type == "1"%>
              <td>支付账户</td>
          <% elsif account.account_type == "2"%>
              <td>银行卡</td>
          <%elsif account.account_type.nil? %>
              <td>没有信息</td>
          <% end %>
          <td><%= account.bank_account_no %></td>
          <% if account.bank_type.nil? %>
              <td>没有信息</td>
          <% else %>
              <td><%= account.bank_type %></td>
          <% end %>

          <% if account.bank_phone.nil? %>
              <td>没有信息</td>
          <% else %>
              <td><%= account.bank_phone %></td>
          <% end %>

          <% if account.area.nil? %>
              <td>没有信息</td>
          <% else %>
              <td><%= account.area %></td>
          <% end %>

          <% if account.balance.nil? %>
              <td>没有信息</td>
          <% else %>
              <td><%= account.balance %></td>
          <% end %>
          <td><%= link_to "解绑账号",account,method: :delete,data: {confirm: "确定解绑?"}%> | <%= link_to "修改密码",change_password_path(account)%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <h2>没有帐户信息</h2>
<% end %>

app/views/users/_orders.html.erb
  <% unless @orders.empty? %>
    <table class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>订单号</th>
        <th>订单状态</th>
        <th>订单金额</th>
        <th>操作</th>
      </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.order_id %></td>
            <td><%= order.order_status %></td>
            <td><%= order.order_sum %></td>
            <% if order.order_status == "完成" %>
                <td><%= link_to "查看", order_path(order) %></td>
            <% elsif order.order_status == "未完成" %>
                <td><%= form_for order do |status|  %>
                      <%= status.hidden_field :order_status,:value => '完成' %>
                      <%= status.submit "确认订单",data:{confirm:"确认订单?"},class: "btn btn-primary btn-xs" %>
                  <% end %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
      <h2>没有订单信息</h2>
  <% end %>

app/views/users/_user.html.erb
<div class="panel panel-default">
    <div class="panel-body">
      <p>用户名:<%= @user.username %></p>
      <p>真实姓名:<%= @user.real_name %></p>
      <p>邮箱:<%= @user.email %></p>
    </div>
</div>

app/views/users/edit.html.erb
<h1>请修改您的个人信息</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= f.label("用户名:")  %>
        <%= f.text_field :username, class: 'form-control' %>
        <%= f.label("邮件:") %>
        <%= f.email_field :email, class: 'form-control' %>
        <% if @user.real_name.nil? %>
        <%= f.label("真实姓名")%>
        <%= f.text_field :real_name, class: 'form-control' %>
        <% end %>
        <%= f.label("手机号:")%>
        <%= f.text_field :phone, class: 'form-control' %>
        <% if @user.idcard.nil?%>
        <%= f.label("身份证") %>
            <%= f.text_field :idcard, class: 'form-control' %>
        <% end %>
        <%= f.label("密码:") %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "确认密码:" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "保存", class: "btn btn-primary col-md-6" %>     <%= link_to "返回",:back ,class: "btn btn-primary col-md-6"%>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="col-md-8">
    <%= form_tag({controller: "users",action: "index"}, method: "get") do %>
        <%= label_tag("请输入关键字") %>
        <%= text_field_tag(:search) %>
        <%= submit_tag("搜索")%>
    <% end %>
  </div>
</div>

<% if  @users.nil? %>
    <h2>用户不存在</h2>
<%else%>
  <table class="table table-striped table-hover table-bordered">
    <thead>
    <tr>
      <th>邮件名</th>
      <th>用户名</th>
      <th>用户真实姓名</th>
      <th>用户类型</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
      <tr>
        <td><%= link_to user.email, user_path(user) %></td>
        <td><%= user.username %></td>
        <td><%= user.real_name %></td>
        <% if user.user_type == "1" %>
        <td>用户</td>
        <% elsif user.user_type == "2" %>
        <td>商户</td>
        <% elsif user.user_type == "3" %>
        <td>管理员</td>
        <% end %>
        <td><%= link_to "删除", user, method: :delete,data: {confirm: "确定删除?"}%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
<% end %>

app/views/users/new.html.erb
<h1>注册</h1>
<div class="row" id="signupform">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label "用户名" %>
        <%= f.text_field :username %>
        <%= f.label "邮箱" %>
        <%= f.email_field :email %>
        <%= f.select :user_type,html_options={用户:"1",商户:"2"}%>
        <%= f.label "登录密码" %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "确认登录密码" %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit "注册账户", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="showsidebar ">
  <div class="list-group">
    <button type="button" class="list-group-item userbtn">用户信息</button>
    <button type="button" class="list-group-item accountbtn">账户信息</button>
    <button type="button" class="list-group-item orderbtn">订单信息</button>
  </div>
</div>
<div class="showpage">
  <div id="userpage">
  <%= render @user %>
  </div>
  <div id="accountpage">
    <%= render "users/accounts" %>
  </div>
  <div id="orderpage">
    <%= render "users/orders" %>
  </div>
  <!--<div id="financepage">-->
  <!--</div>-->
</div>