config/routes.rb
Rails.application.routes.draw do
  get 'finances/index'

  get 'finances/show'

  get 'sessions/new'

  get    'finances/u_search/:id' => 'finances#u_search', as: 'u_search'

  get    'finances/a_search/:id' => 'finances#a_search', as: 'a_search'

  get    'orderinfos'      => 'orderinfos#index'

  get    'orderinfos/:id'  => 'orderinfos#show' , as: 'orderinfo'

  get    'orders/:id'      => 'orders#show', as: 'order'

  get    'orders/:id/update'      => 'orders#update', as: 'update'

  root   'pages#home'

  get    'users/new'       =>  'users#new', as: 'signup'

  get    'users/:id'       =>  'users#show', as: 'user'
  
  get    'users'           =>  'users#index'

  get    'users/:id/edit'  =>  'users#edit'

  get    'accounts/new', as: 'create_account'

  get    'accounts/:id/edit'   =>  'accounts#edit', as:'change_password'

  get    'accounts/:id'    =>  'accounts#show', as: 'account'

  get    'orders'          =>  'orders#index'

  get    'login'           =>  'sessions#new'

  post   'login'           =>  'sessions#create'

  delete 'logout'          =>  'sessions#destroy'

  namespace :api do
    get 'finances/search'           =>  'finances#search'
    get 'finances/count'            =>  'finances#count'
    resources :finances
  end

  resources :users, :accounts, :orders, :orderinfos

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :users, through: :u_orelations
  has_many :u_orelations
  has_one :orderinfo
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper
  def show
    @order = Order.find(params[:id])
    @orderinfo = @order.orderinfo
  end

  def index
    search_order
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(order_params)
      flash[:success] = "确认成功"
      redirect_to @order
    end
  end

  def destroy
    Order.find(params[:id]).destroy
    flash[:success] = "订单删除成功"
    redirect_to orders_url
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def search_order
    if params[:order_id].present? && params[:commit] == "搜索"
      order = Order.where("order_id = ?", params[:order_id])
      if order.present?
        @orders = order.paginate(page: params[:page])
      end
    elsif params[:order_id].nil? && params[:commit] == "搜索"
      @orders = {}
    elsif params[:order_id].nil? && params[:commit].nil?
      @orders = Order.paginate(page: params[:page]).per_page(10)
    end
  end
end

app/views/orders/index.html.erb
<div class="container">
  <%= form_tag({controller: "orders",action: "index"}, method: "get") do %>
      <%= label_tag(:order_id,"订单号:") %>
      <%= text_field_tag(:order_id) %>
      <%= submit_tag("搜索")%>
  <% end %>
</div>
<% if  @orders.nil? %>
    <h2>订单不存在</h2>
<%else%>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Id</th>
          <th>订单号</th>
          <th>订单金额</th>
          <th>订单状态</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%=link_to order.order_id, order_path(order) %></td>
          <td><%= order.order_sum %></td>
          <td><%= order.order_status %></td>
          <% if order.order_status == "未完成"  %>
          <td>
            <%= form_for order do |status| %>
                <%= status.select :order_status,html_options={锁住订单:"锁住",无效订单:"无效"}%>
                <%= status.submit "变更",data:{confirm:"确认变更订单状态?"},class: "btn btn-primary btn-xs"%>
            <% end %>
          </td>
          <% elsif order.order_status == "锁住" %>
          <td>
            <%= form_for order do |status|%>
                <%= status.select :order_status,html_options={解锁订单:"未完成",无效订单:"无效"}%>
                <%= status.submit "变更",data:{confirm:"确认变更订单状态?"},class: "btn btn-primary btn-xs"%>
            <% end %>
          </td>
          <% elsif order.order_status == "无效" %>
          <td>
            <%= link_to "删除", order, method: :delete,data: {confirm: "确定删除?"}%>
          </td>
          <% end %>
          <td><%= link_to "查看",order_path(order) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
<% end %>

app/views/orders/show.html.erb
<table class="table table-bordered">
  <thead>
      <tr>
        <th>买家账号</th>
        <th>商家账号</th>
        <th>商品信息</th>
        <th>操作</th>
      </tr>
  </thead>
  <tbody>
      <% if admin? %>
      <tr>
        <td><%= link_to @orderinfo.buyer_account, orderinfo_path(@orderinfo.buyer_account) %></td>
        <td><%= link_to @orderinfo.seller_account, orderinfo_path(@orderinfo.seller_account) %></td>
        <td><%= @orderinfo.product_info%></td>
        <td><%= link_to "返回上一页",:back %></td>
      </tr>
      <% else %>
      <tr>
        <td><%= @orderinfo.buyer_account %></td>
        <td><%= @orderinfo.seller_account %></td>
        <td><%= @orderinfo.product_info%></td>
        <td><%= link_to "返回上一页",:back %></td>
      </tr>
      <% end %>
  </tbody>
</table>