config/routes.rb
Rails.application.routes.draw do
  get 'finances/index'

  get 'finances/show'

  get 'sessions/new'

  get    'finances/u_search/:id' => 'finances#u_search', as: 'u_search'

  get    'finances/a_search/:id' => 'finances#a_search', as: 'a_search'

  get    'orderinfos'      => 'orderinfos#index'

  get    'orderinfos/:id'  => 'orderinfos#show' , as: 'orderinfo'

  get    'orders/:id'      => 'orders#show', as: 'order'

  get    'orders/:id/update'      => 'orders#update', as: 'update'

  root   'pages#home'

  get    'users/new'       =>  'users#new', as: 'signup'

  get    'users/:id'       =>  'users#show', as: 'user'
  
  get    'users'           =>  'users#index'

  get    'users/:id/edit'  =>  'users#edit'

  get    'accounts/new', as: 'create_account'

  get    'accounts/:id/edit'   =>  'accounts#edit', as:'change_password'

  get    'accounts/:id'    =>  'accounts#show', as: 'account'

  get    'orders'          =>  'orders#index'

  get    'login'           =>  'sessions#new'

  post   'login'           =>  'sessions#create'

  delete 'logout'          =>  'sessions#destroy'

  namespace :api do
    get 'finances/search'           =>  'finances#search'
    get 'finances/count'            =>  'finances#count'
    resources :finances
  end

  resources :users, :accounts, :orders, :orderinfos

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <smal>
    By Pokr
  </smal>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse head">
  <div class="container">
    <%= link_to "支付结算账户管理系统", root_path,id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "首页",root_path%></li>

        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.username %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "个人信息", current_user%></li>
                <li><%= link_to "设置", edit_user_path(current_user)%></li>
                <li><%= link_to "账务信息", u_search_path(current_user) %></li>
                <% if admin? %>
                  <li><%= link_to "用户列表", users_path %></li>
                  <li><%= link_to "订单列表", orders_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "退出",logout_path, method: :delete%></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "注册", signup_path %></li>
            <li><%= link_to "登录", login_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaymentcrmSys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
<%= render "layouts/header" %>
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
<div class="main">
  <%= yield %>
</div>


<%= render "layouts/footer" %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>