config/routes.rb
Rails.application.routes.draw do
  get 'finances/index'

  get 'finances/show'

  get 'sessions/new'

  get    'finances/u_search/:id' => 'finances#u_search', as: 'u_search'

  get    'finances/a_search/:id' => 'finances#a_search', as: 'a_search'

  get    'orderinfos'      => 'orderinfos#index'

  get    'orderinfos/:id'  => 'orderinfos#show' , as: 'orderinfo'

  get    'orders/:id'      => 'orders#show', as: 'order'

  get    'orders/:id/update'      => 'orders#update', as: 'update'

  root   'pages#home'

  get    'users/new'       =>  'users#new', as: 'signup'

  get    'users/:id'       =>  'users#show', as: 'user'
  
  get    'users'           =>  'users#index'

  get    'users/:id/edit'  =>  'users#edit'

  get    'accounts/new', as: 'create_account'

  get    'accounts/:id/edit'   =>  'accounts#edit', as:'change_password'

  get    'accounts/:id'    =>  'accounts#show', as: 'account'

  get    'orders'          =>  'orders#index'

  get    'login'           =>  'sessions#new'

  post   'login'           =>  'sessions#create'

  delete 'logout'          =>  'sessions#destroy'

  namespace :api do
    get 'finances/search'           =>  'finances#search'
    get 'finances/count'            =>  'finances#count'
    resources :finances
  end

  resources :users, :accounts, :orders, :orderinfos

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessor :paypassword
  belongs_to :user
  has_many :basics, as: :finance
  validates :bank_account, presence: true, length: {maximum:50},uniqueness: { case_sensitive: false }
  validates :bank_account_no, presence: true, length: {maximum:50 }
  validates :bank_phone, length: {maximum: 20}
  validates :paypassword, presence: true, length: { minimum: 6 },allow_nil: true

  include ActiveModel::Validations


    validate do |record|
      record.errors.add(:paypassword, :blank) unless record.paypassword_digest.present?
    end

    validates_length_of :paypassword, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
    validates_confirmation_of :paypassword, allow_blank: true

    if respond_to?(:attributes_protected_by_default)
      def self.attributes_protected_by_default #:nodoc:
        super + ['paypassword_digest']
      end
    end

    #attr_reader :paypassword


    def paypassword=(unencrypted_password)
      if unencrypted_password.nil?
        self.paypassword_digest = nil
      elsif !unencrypted_password.empty?
        @paypassword = unencrypted_password
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        self.paypassword_digest = BCrypt::Password.create(unencrypted_password, cost: cost)
      end
    end

    def paypassword_confirmation=(unencrypted_password)
      @paypassword_confirmation = unencrypted_password
    end

    def authenticate(unencrypted_password)
      BCrypt::Password.new(paypassword_digest) == unencrypted_password && self
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      flash.now[:success] = "绑定成功"
      redirect_to @account
    else
      render 'new'
    end
  end

  def destroy
    Account.find(params[:id]).destroy
    flash.now[:success] = "解绑账号"
    redirect_to @current_user
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(change_password)
      flash[:success] = "修改成功"
      redirect_to @account
    else
      flash[:danger] = "更新失败"
      render 'edit'
    end
  end

  def edit
    @account = Account.find(params[:id])
  end


  private
  def account_params
    params.require(:account).permit(:user_id, :bank_account, :bank_account_no,:bank_phone,:bank_type,:account_type,:balance,:area,:paypassword,:paypassword_confirmation)
  end

  def change_password
    params.require(:account).permit(:paypassword,:paypassword_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<h1>请修改支付密码</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@account) do |a| %>
        <%= a.label("新支付密码:") %>
        <%= a.password_field :paypassword, class: 'form-control' %>
        <%= a.label :paypassword_confirmation, "确认新支付密码:" %>
        <%= a.password_field :paypassword_confirmation, class: 'form-control' %>
        <%= a.submit "保存", class: "btn btn-primary col-md-6" %><%= link_to "返回",:back, class: "btn btn-primary col-md-6" %>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<h1>绑定账户</h1>
<div class="row" id="signupform">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@account) do |a| %>
        <%= render 'shared/account_error_messages' %>
        <%= a.label "银行账户" %>
        <%= a.text_field :bank_account %>
        <%= a.label "银行卡号" %>
        <%= a.text_field :bank_account_no %>
        <%= a.label "银行类型"%>
        <%= a.text_field :bank_type %>
        <%= a.label "银行电话"%>
        <%= a.text_field :bank_phone %>
        <%= a.label "地区" %>
        <%= a.text_field :area %>
        <%= a.hidden_field :user_id,:value => session[:user_id]%>
        <%= a.hidden_field :account_type,:value =>'2' %>
        <%= a.label "支付密码" %>
        <%= a.password_field :paypassword %>
        <%= a.label :paypassword_confirmation, "确认支付密码" %>
        <%= a.password_field :paypassword_confirmation %>
        <%= a.submit "绑定账户", class: "btn btn-primary" %><%= link_to "返回",:back %>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt><p>账户名称:</p></dt>
      <dd><p><%= @account.bank_account %></p></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><p>账户卡号:</p></dt>
      <dd><p><%= @account.bank_account_no %></p></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><p>所属银行:</p></dt>
      <% if @account.bank_type == "" %>
          <dd>无</dd>
      <% else %>
          <dd><p><%= @account.bank_type %></p></dd>
      <% end %>
    </dl>
    <dl class="dl-horizontal">
      <dt><p>账户类型:</p></dt>
      <% if @account.account_type == "1" %>
      <dd><p>支付账户</p></dd>
      <% elsif  @account.account_type == "2"%>
      <dd><p>银行卡</p></dd>
      <% end %>
    </dl>
    <dl class="dl-horizontal">
      <dt><p>账户操作</p></dt>
      <dd><%= link_to "账务查询", a_search_path(@account) %></dd>
    </dl>
  </div>
</div>